### ISSUE TITLE
Question: Is the admin section done in Nuxt?

### ISSUE THREAD

**Issue by connecteev** [adr1enbe4udou1n/laranuxt-starter-kit#1]
@adr1enbe4udou1n just discovered your repo.
I understand that the [frontend](https://laranuxt.okami101.io/about-us) is in Nuxt.
Is the [admin section here](https://laranuxt.okami101.io/admin/) built in Laravel, or is it using Nuxt over Laravel APIs? If it's the latter (Nuxt over Laravel APIs) then I will spend some time installing and trying this out.

**Comment by adr1enbe4udou1n** [comment]
The logo was indeed confusing, i just change it by coreui.
The admin UI section is 100% custom Vue SPA app integrated inside Laravel resources.
Nuxt is only useful at frontend site for SEO / SSR.

**Comment by connecteev** [comment]
I see..thanks! 
if coreUI is in vue, then it's still interesting....components could be ported to nuxt. I've been looking for a nuxt+laravel cms and not found one.
